services:
  query-ai-db-vector:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${QA_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${QA_DB_NAME:-query-ai}"
      POSTGRES_USER: "${QA_DB_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${QA_DB_PASSWORD:-mypassword}"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
